### ISSUE TITLE
Hint is cut when inside an overflow hidden

### ISSUE THREAD

**Issue by ephigabay** [chinchang/hint.css#78] opened 2014-05-26 13:52 UTC
Hey,
if the element I'm using hint on is inside an overflow hidden element, the tooltip is being cut.
Is there any option to fix this issue? Maybe by making a fixed position instead of absolute.

Thanks :)

**Comment by antivanov** [comment] 2015-11-13 15:42
Having the same issue, setting CSS `overflow` property on any ancestor DOM element of the current element that has the `data-hint` attribute will result in the hint being cut. 

This seems to be the correct behavior according to the standard, reproducible in all browsers (IE, Firefox, Chrome). 

The limitation of the current implementation is that hints are "local" and not "global" in the document flow, then setting the `overflow` property just makes it visible by cutting the hint. 

Most likely this and similar issues cannot be fixed with this purely CSS approach. If you are having this issue at the moment you may want to use some alternative hint library that uses some JavaScript and positions the hint in the document flow globally.

**Comment by chinchang** [comment] 2016-01-31 07:51
Like @antivanov explained, this happens due to the defined behavior of the `overflow` property and **Hint** tooltips being local to the targeted elements.

As of now, there is no solution to this problem except avoiding the `overflow` property on the parent or moving the tooltip to some parent element above the `overflow` element in html.

**Closed by chinchang** 2016-01-31 07:51 UTC
Labels: wontfix
