### ISSUE TITLE
Needs more positioning options

### ISSUE THREAD

**Issue by djiest** [chinchang/hint.css#94] opened 2015-09-16 15:18 UTC
Great tool! It could however use more positioning options, for more flexibility, eg.
* north or top
* north-east or top-right
* east or right
* south-east or bottom-right
* south or bottom
* south-west or bottom-left
* west or left
* north-west or top-left

See image for an example where positioning is 'bottom'. Positioning on 'south-west' or 'bottom-left' seems more appropiate.

![image](https://cloud.githubusercontent.com/assets/1582516/9909161/46ca119e-5c97-11e5-836a-fd51d8240d12.png)

**Comment by vhmth** [comment] 2015-11-15 02:06
+1 any ETA on this, or is it on the back burner?

**Comment by chinchang** [comment] 2015-11-16 18:19
Agree, this could be helpful. Will look into it this coming weekend.

**Comment by jonataswalker** [comment] 2015-11-20 12:21
This would be great.

**Comment by joaocunha** [comment] 2015-11-20 14:14
Duplicate of #71.

**Comment by chinchang** [comment] 2015-11-21 14:02
Looking for opinions on the usage of classes for other positions.
Which one would you prefer for a top-left tooltip: `hint--top-left` or `hint--top  hint--left`?

**Comment by jonataswalker** [comment] 2015-11-21 15:06
+1 `hint--top-left` to decrease the number of classes.

**Comment by chinchang** [comment] 2015-11-22 11:59
Here is my wip branch for this issue:https://github.com/chinchang/hint.css/tree/more-position-classes

Checkout the new demo -> https://rawgit.com/chinchang/hint.css/more-position-classes/demo.html

It now has all the positioning options that any JavaScript library like tipsy would give.

Some more testing and will get it ready for master.

**Comment by brillout** [comment] 2015-12-14 18:24
+1

**Comment by chinchang** [comment] 2016-01-25 10:35
fixed :)

**Closed by chinchang** 2016-01-25 10:35 UTC
