### ISSUE TITLE
input cannt show tooltip

### ISSUE THREAD

**Issue by askie** [chinchang/hint.css#141] opened 2016-06-02 12:41 UTC
code like below:
`
<input type="text" class="hint-always hint--top" aria-label="msg......" >
`
cannt see the tooltip!

**Comment by chinchang** [comment] 2016-06-02 22:48
@askie You'll have to wrap your input in some other tag and put tooltip on that because inputs cannot have pseudo elements.

Closing as duplicate of #49

**Closed by chinchang** 2016-06-02 22:48 UTC
